src/notepad/urls.py
from django.urls import path

from . import views


app_name = 'notepad'
urlpatterns = [
    path('', views.NotepadCreateView.as_view(), name='create'),
    path('<uuid:slug>', views.NotepadUpdateView.as_view(), name='update'),
    path('about', views.AboutView.as_view(), name='about'),
]

src/securenotepad/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views


# Personalized admin site settings like title and header
admin.site.site_title = f"{settings.PROJECT_NAME} Site Admin"
admin.site.site_header = f"{settings.PROJECT_NAME} Administration"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notepad.urls')),
    path('manifest.json', views.manifest, name='manifest'),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/notepad/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site


class Notepad(models.Model):
    slug = models.UUIDField(default=uuid.uuid4, unique=True)
    notepad = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_url(self, request):
        site = get_current_site(request)
        return f'{request.scheme}://{site.domain}{self.absolute_url}'

    @property
    def absolute_url(self):
        return reverse('notepad:update', kwargs={'slug': self.slug})

src/notepad/forms.py
from django import forms

from .models import Notepad


class NotepadForm(forms.ModelForm):
    class Meta:
        model = Notepad
        fields = [
            'notepad',
        ]

src/notepad/views.py
from django.views import generic

from .mixins import NotepadCreateUpdateMixin


class NotepadCreateView(NotepadCreateUpdateMixin, generic.CreateView):
    pass


class NotepadUpdateView(NotepadCreateUpdateMixin, generic.UpdateView):
    pass


class AboutView(generic.TemplateView):
    template_name = 'notepad/about.html'

src/securenotepad/views.py
from django.shortcuts import render


def manifest(request):
    return render(request, 'manifest.json', content_type='application/json')

src/notepad/templates/notepad/about.html
{% extends 'notepad/layout.html' %}

{% block title %}About{% endblock %}

{% block navbar-left %}
    {% include '_navbar.html' with active_link='about' %}
{% endblock %}

{% block page-content-class %}has-sticky-footer{% endblock %}

{% block content %}
    <div class="pt-5">
        <h4>How it works:</h4>
        <p class="pt-3">It's quite simple, actually. Create a notepad, encrypt it with your password, and get a direct link to it. No ads, tracking, or extra features, just what it says on the tin.</p>
        <p>Your password is never sent to the server. Your content is encrypted and decrypted using <a href="https://en.wikipedia.org/wiki/Advanced_Encryption_Standard">AES</a> on your device. Anyone visiting your Notepad's link will just see gibberish, and the server only sees the encrypted content. For example, encrypting <code>hello</code> with <code>123</code> as the password will produce <code>U2FsdGVkX1/eCCswPja8xltMeWVBhfn2EJgUW73IZPk=</code>. A stronger password will be harder to decrypt.</p>
        <p>Unique links are generated randomly, and therefore add an additional layer of anonymity. The chance of two links being the same are 1 in 2^128.</p>
        <p><a href="https://bitbucket.org/sheya/securenotepad"><i class="fab fa-bitbucket"></i> View the source code on BitBucket</a></p>
    </div>

    <nav class="navbar fixed-bottom navbar-dark bg-dark footer-navbar">
        <div class="mx-auto small text-light">© {% now 'Y' %} <a class="text-light" target="_blank" href="https://sheyabernstein.com">Sheya Bernstein</a></div>
    </nav>
{% endblock %}

src/notepad/templates/notepad/create_update.html
{% extends 'notepad/layout.html' %}
{% load static notepad %}

{% block title %}{% if object.pk %}Work on Notepad{% else %}New Notepad{% endif %}{% endblock %}

{% block navbar-left %}
    {% include '_navbar.html' with active_link='new' %}
{% endblock %}

{% block content %}
    <div class="loader text-center">
        <div class="lds-hourglass"></div>
    </div>
    <div class="pt-5 show-on-load" style="display: none;">
        <div class="input-group mb-4 link-container {% if not object.pk %}d-none{% endif %}">
            <div class="input-group-prepend d-none d-md-block">
                <span class="input-group-text bg-dark">This Notepad is available at:</span>
                <span class="d-none" id="notepad-link">{% full_url object %}</span>
            </div>
            <input type="text" class="form-control" id="link" aria-describedby="notepad-link" readonly value="{% full_url object %}">
            <div class="input-group-append">
                <button class="btn btn-secondary bg-dark copy" title="Copy" onclick="copyLink(this)"><i class="fas fa-copy"></i></button>
            </div>
        </div>

        <div>
            <div id="tiny"></div>
        </div>

        <form class="notepad-form" method="post" autocomplete="nope">
            {% csrf_token %}
            <input type="hidden" id="isnew" value="{% if form.instance.pk %}1{% else %}0{% endif %}">
            <div class="d-none">{{ form }}</div>
        </form>

        <div class="buttons mt-3 text-right">
            <button class="btn btn-primary save-btn" {% if not object.pk %}disabled{% endif %} type="button" onclick="encrypt(this)">Encrypt and Save</button>
        </div>

        <div class="meta {% if not object.pk %}d-none{% endif %} mb-3">
            <div class="small">Created <span class="created-at">{{ object.created_at }}</span></div>
            <div class="small">Last updated <span class="updated-at">{{ object.updated_at }}</span></div>
        </div>
    </div>
{% endblock %}

src/notepad/templates/notepad/layout.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'notepad/js/tinymce.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="{% static 'notepad/js/notepad.js' %}"></script>
{% endblock %}

src/templates/_brandname.html
Secure Notepad

src/templates/_description.html
Create a notepad, encrypt it with your password, and get a direct link to it.

src/templates/_navbar.html
<li class="nav-item ml-3 {% if active_link == 'new' %}active{% endif %}">
    <a class="nav-link" href="{% url 'notepad:create' %}">New{% if active_link == 'new' %} <span class="sr-only">(current)</span>{% endif %}</a>
</li>
<li class="nav-item ml-3 {% if active_link == 'about' %}active{% endif %}">
    <a class="nav-link" href="{% url 'notepad:about' %}">How It Works{% if active_link == 'about' %} <span class="sr-only">(current)</span>{% endif %}</a>
</li>

src/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="theme-color" content="#303030">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% include '_description.html' %}">

    <link rel="manifest" href="{% url 'manifest' %}">
    <link rel="icon" href="{% static 'img/logo-dark.png' %}">

    <!-- CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/darkly/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block head %}{% endblock %}

    <title>{% block title %}{% endblock %} | {% include '_brandname.html' %}</title>
</head>
<body>

    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark main-navbar">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/logo-light.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span class="pl-3">{% include '_brandname.html' %}</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% block navbar-left %}
                        {% include '_navbar.html' %}
                    {% endblock %}
                </ul>
            </div>
        </nav>
    {% endblock %}

    {% block messages %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} m-2">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}
    {% endblock %}

    <div class="container page-content {% block page-content-class %}{% endblock %}">{% block content %}{% endblock %}</div>

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>